In [7]:

import pandas as pd

In [12]:
data=pd.read_csv("bank-additional.csv",sep=",")

In [13]:
data

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,45,entrepreneur,married,university.degree,unknown,yes,yes,cellular,aug,mon,...,2,999,0,nonexistent,1.4,93444.0,-36.1,4965.00,5228.1,no
1,29,technician,single,university.degree,no,yes,yes,cellular,aug,wed,...,3,999,0,nonexistent,1.4,93444.0,-36.1,4967.00,5228.1,no
2,40,management,married,high.school,no,no,yes,cellular,aug,wed,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4965.00,5228.1,no
3,38,technician,married,professional.course,no,yes,no,cellular,aug,mon,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4965.00,5228.1,yes
4,34,admin.,married,university.degree,no,no,no,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4963.00,5228.1,no
5,48,technician,married,university.degree,no,no,no,cellular,aug,thu,...,7,999,0,nonexistent,1.4,93444.0,-36.1,4962.00,5228.1,no
6,44,services,married,professional.course,no,no,no,cellular,aug,mon,...,2,999,0,nonexistent,1.4,93444.0,-36.1,4.97,5228.1,no
7,39,management,married,high.school,no,no,no,cellular,aug,fri,...,3,999,0,nonexistent,1.4,93444.0,-36.1,4966.00,5228.1,no
8,31,admin.,married,university.degree,no,yes,no,cellular,aug,thu,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4964.00,5228.1,no
9,31,technician,single,high.school,no,yes,yes,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4966.00,5228.1,yes
10,31,admin.,married,university.degree,no,yes,no,cellular,aug,thu,...,5,999,0,nonexistent,1.4,93444.0,-36.1,4962.00,5228.1,no
11,32,technician,single,university.degree,no,no,no,cellular,aug,tue,...,12,999,0,nonexistent,1.4,93444.0,-36.1,4966.00,5228.1,no
12,59,services,married,basic.4y,unknown,no,no,cellular,aug,thu,...,7,999,0,nonexistent,1.4,93444.0,-36.1,4963.00,5228.1,no
13,45,admin.,single,university.degree,no,no,no,cellular,aug,thu,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4964.00,5228.1,yes
14,52,admin.,married,unknown,no,no,no,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4968.00,5228.1,no
15,51,blue-collar,married,basic.4y,unknown,yes,yes,cellular,aug,thu,...,2,999,0,nonexistent,1.4,93444.0,-36.1,4964.00,5228.1,no
16,50,admin.,married,basic.9y,unknown,yes,no,cellular,aug,thu,...,3,999,0,nonexistent,1.4,93444.0,-36.1,4963.00,5228.1,no
17,29,management,married,university.degree,no,no,yes,cellular,aug,wed,...,2,999,0,nonexistent,1.4,93444.0,-36.1,4967.00,5228.1,no
18,41,technician,married,professional.course,no,yes,no,cellular,aug,mon,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4963.00,5228.1,no
19,40,admin.,divorced,university.degree,no,yes,no,cellular,aug,mon,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4965.00,5228.1,no
20,32,technician,single,university.degree,no,yes,no,cellular,aug,wed,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4965.00,5228.1,no
21,54,blue-collar,married,basic.4y,no,yes,no,cellular,aug,tue,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4963.00,5228.1,no
22,50,services,married,unknown,no,yes,no,cellular,aug,thu,...,2,999,0,nonexistent,1.4,93444.0,-36.1,4968.00,5228.1,no
23,38,admin.,married,university.degree,no,yes,no,cellular,aug,tue,...,6,999,0,nonexistent,1.4,93444.0,-36.1,4965.00,5228.1,no
24,57,services,married,professional.course,unknown,no,no,cellular,aug,mon,...,2,999,0,nonexistent,1.4,93444.0,-36.1,4965.00,5228.1,no
25,47,technician,married,university.degree,no,yes,no,cellular,aug,wed,...,7,999,0,nonexistent,1.4,93444.0,-36.1,4964.00,5228.1,no
26,52,blue-collar,married,basic.9y,no,no,no,cellular,aug,fri,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4966.00,5228.1,yes
27,44,admin.,married,high.school,no,yes,no,cellular,aug,fri,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4964.00,5228.1,no
28,54,self-employed,married,high.school,no,no,no,cellular,aug,tue,...,3,999,0,nonexistent,1.4,93444.0,-36.1,4963.00,5228.1,no
29,51,blue-collar,married,basic.6y,no,no,no,cellular,aug,fri,...,1,999,0,nonexistent,1.4,93444.0,-36.1,4964.00,5228.1,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4089,36,blue-collar,married,basic.6y,unknown,no,no,telephone,may,fri,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4090,52,technician,married,basic.9y,no,yes,no,telephone,may,thu,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4.86,5191.0,no
4091,28,blue-collar,married,basic.9y,no,no,yes,telephone,may,fri,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4092,52,services,married,basic.9y,unknown,no,no,telephone,may,thu,...,3,999,0,nonexistent,1.1,93994.0,-36.4,4.86,5191.0,no
4093,35,technician,divorced,professional.course,no,no,yes,telephone,may,fri,...,3,999,0,nonexistent,1.1,93994.0,-36.4,4855.00,5191.0,no
4094,30,blue-collar,single,basic.9y,no,yes,yes,telephone,may,mon,...,4,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4095,35,admin.,married,basic.9y,no,no,no,telephone,may,tue,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4096,43,unemployed,married,university.degree,unknown,no,no,telephone,may,thu,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4.86,5191.0,no
4097,34,admin.,married,university.degree,no,yes,no,telephone,may,fri,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4859.00,5191.0,no
4098,35,technician,married,professional.course,no,no,no,telephone,may,tue,...,3,999,0,nonexistent,1.1,93994.0,-36.4,4856.00,5191.0,no
4099,50,blue-collar,divorced,high.school,unknown,no,yes,telephone,may,mon,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4100,33,blue-collar,married,basic.9y,no,unknown,unknown,telephone,may,wed,...,3,999,0,nonexistent,1.1,93994.0,-36.4,4856.00,5191.0,no
4101,57,technician,married,professional.course,no,yes,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4858.00,5191.0,yes
4102,46,housemaid,married,basic.4y,no,no,no,telephone,may,wed,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4858.00,5191.0,no
4103,54,management,single,basic.9y,no,yes,no,telephone,may,mon,...,3,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4104,36,services,married,high.school,no,no,yes,telephone,may,tue,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4105,40,admin.,single,university.degree,no,yes,yes,telephone,may,mon,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4106,47,blue-collar,divorced,basic.9y,unknown,yes,no,telephone,may,wed,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4107,31,admin.,married,university.degree,no,yes,no,telephone,may,thu,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4.86,5191.0,no
4108,52,blue-collar,married,basic.9y,unknown,yes,no,telephone,may,fri,...,3,999,0,nonexistent,1.1,93994.0,-36.4,4855.00,5191.0,no
4109,54,blue-collar,married,basic.4y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4858.00,5191.0,no
4110,44,admin.,married,university.degree,no,yes,no,telephone,may,thu,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4.86,5191.0,no
4111,42,technician,single,basic.9y,no,yes,no,telephone,may,wed,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4112,54,technician,married,professional.course,no,yes,yes,telephone,may,mon,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4113,29,admin.,married,university.degree,no,yes,no,telephone,may,thu,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4.86,5191.0,no
4114,43,blue-collar,married,basic.4y,unknown,yes,yes,telephone,may,tue,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4115,38,management,married,high.school,unknown,no,no,telephone,may,thu,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4.86,5191.0,no
4116,33,services,married,high.school,no,no,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4117,43,services,married,high.school,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93994.0,-36.4,4857.00,5191.0,no
4118,53,housemaid,divorced,basic.6y,unknown,unknown,unknown,telephone,may,fri,...,2,999,0,nonexistent,1.1,93994.0,-36.4,4855.00,5191.0,no